### ISSUE TITLE
Support for MapMvcAttributeRoutes()

### ISSUE THREAD

**Issue by jepzen** [MattHoneycutt/SpecsFor#77]
iIn my setup  have this line

    Config.BuildRoutesUsing(r => RouteConfig.RegisterRoutes(r));

But when I run the tests it throws an exception when trying to execute 

    routes.MapMvcAttributeRoutes();

'This method cannot be called during the application's pre-start initialization phase.'

**Comment by MattHoneycutt** [comment]
Unfortunately this is a limitation of the current version of ASP.NET MVC.   There is a way around it though.

First, modify your RouteConfig class so that it's possible to invoke it *without* triggering a call to MapMvcAttributeRoutes.  You could do that by adding an optional parameter that controls whether or not to map attribute routes.

Next, in your spec project, add a reference to the SpecsFor.Helpers.Web NuGet package, and use the MapMvcAttributeRoutesForTestingFromAssemblyContaining<T> extension method (found in the SpecsFor.Helpers.Web.Mvc namespace) to register your attribute routes instead.  You can call it in your setup fixture class.  It might look something like this:

			Config.BuildRoutesUsing(r =>
			{
				RouteConfig.RegisterRoutes(r, loadAttributeRoutes:false);
				r.MapMvcAttributeRoutesForTestingFromAssemblyContaining<HomeController>();
			});


Remember that the order of route registration matters, so be sure the order you load your attribute routes matches how you're doing it in your web app.

I hope that helps!
