### ISSUE TITLE
SpecsFor Support for Executing SpecsFor Automatically?

### ISSUE THREAD

**Issue by jt4000** [MattHoneycutt/SpecsFor#92]
1.
Do I need to make manual coding in order to execute IIS express before using SpecsFor?

2.
Does SpecsFor have support for executing the IIS express automatically?

3.
Does it work to use Asp.net mvc for SpecsFor?
 
Thanks!

**Comment by MattHoneycutt** [comment]
If you are using IIS Express, you probably want SpecsFor.Mvc, which has everything you need to spin up and host your app in IIS Express.  

That said, you can still write unit and integration tests against ASP.NET apps without using SpecsFor.Mvc.  You only need SpecsFor.Mvc if you want to do full end-to-end testing through your application's UI.  Otherwise, testing something like an MVC controller is no different than testing any other class, at least at a high level.
